### ISSUE TITLE
Practica3

### ISSUE THREAD

**Issue by BautistaLizbeth** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-equipo-f4#1]
[P3_Mapas de Karnaugh[1].pdf](https://github.com/user-attachments/files/18050326/P3_Mapas.de.Karnaugh.1.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
