### ISSUE TITLE
 Practica Utilizando Mapas de karnaught

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-equipo-f4#2]
[Practica 3 mate discretas.pdf](https://github.com/user-attachments/files/18056975/Practica.3.mate.discretas.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
